DB_HOST = 'YOUR_DB_HOST'
DB_PORT = 'YOUR_DB_PORT'
MAIN_DB_NAME = 'YOUR_MAIN_DB_NAME'
LOCAL_DB_NAME = 'YOUR_LOCAL_DB_NAME'
DB_USER = 'YOUR_DB_USER'
DB_PASS = 'YOUR_DB_PASSWORD'

SQLALCHEMY_MAIN_DATABASE_URL = f"postgresql://{DB_USER}:{DB_PASS}@{DB_HOST}:{DB_PORT}/{MAIN_DB_NAME}"
ASYNC_SQLALCHEMY_MAIN_DATABASE_URL = f"postgresql+asyncpg://{DB_USER}:{DB_PASS}@{DB_HOST}:{DB_PORT}/{MAIN_DB_NAME}"

SQLALCHEMY_LOCAL_DATABASE_URL = f"postgresql://{DB_USER}:{DB_PASS}@{DB_HOST}:{DB_PORT}/{LOCAL_DB_NAME}"
ASYNC_SQLALCHEMY_LOCAL_DATABASE_URL = f"postgresql+asyncpg://{DB_USER}:{DB_PASS}@{DB_HOST}:{DB_PORT}/{LOCAL_DB_NAME}"

BOT_TOKEN = 'YOUR_TELEGRAM_BOT_TOKEN'

add_group_link = f"https://t.me/@JustAskX_bot?startgroup=newgroups&admin=manage_chat+change_info+delete_messages+restrict_members+invite_users+promote_members"

BALANCER_PORT = 8030
BALANCER_URL = 'YOUR_BALANCER_URL'

TELEGRAM_BOT_USERS_PORT = 8029
TELEGRAM_BOT_USERS_URL = 'YOUR_USERS_URL'

TELEGRAM_BOT_GROUPS_PORT = 8031
TELEGRAM_BOT_GROUPS_URL = 'YOUR_GROUPS_URL'

ENV_TYPE = 'YOUR_ENV_TYPE'


deepseek_BASE_URL = "https://api.deepseek.com"
deepseek_API_KEY = "sk-78da1a164bd14bb484d11571ff96ef9e"
deepseek_MODEL = "deepseek-chat"